stages:
  -test


test_run_job:
  stage: test
  tags:
    -test-runner
  only:
    -lesson_8
  script:
    -mvn clean test -DsuiteXmlFile=testNG.xml
  artifacts:
    when: always
    paths:
      - allure-results